java \
    -Dtransitime.db.dbName=stif \
    -Dtransitime.db.dbType=postgresql \
    -Dtransitime.db.dbUsername=postgres \
    -Dtransitime.db.dbPassword=transitime \
    -Dtransitime.hibernate.configFile=hibernate.cfg.xml \
    -Dhibernate.connection.url=jdbc:postgresql://$POSTGRES_PORT_5432_TCP_ADDR:$POSTGRES_PORT_5432_TCP_PORT/stif \
    -Dhibernate.connection.username=postgres \
    -Dhibernate.connection.password=transitime \
    -cp transitime.jar org.transitime.applications.GtfsFileProcessor \
    -gtfsUrl "http://ratp.spiralo.net/stif_gtfs_enhanced_rer_latest.zip"
